### ISSUE TITLE
Feature-based System

### ISSUE THREAD

**Issue by figmentc** [jgc128/mednli_baseline#1]
Is the data/code for the feature-based model in the paper available by any chance?

**Comment by jgc128** [comment]
Hi,

I just added the code for the feature-based system. It achieves about 0.52 accuracy on the dev set. 

To use it, just run the `python train_feature_based.py` command (you'd need to do `git pull` and `pip install -r requirements.txt`).

Feel free to re-open this issue if you have any troubles running the code!

**Comment by figmentc** [comment]
Thanks for the quick response! I was wondering if the UMLS concept similarity distance was also used in the feature-based approach as described in the paper.

**Comment by jgc128** [comment]
They were used for the experiments in the paper; however, this repository contains a simplified baselines that does not require UMLS installation. If you need those features, you can have a look at the function [here](https://github.com/jgc128/mednli/blob/d7c9007a45a265dbfbb8cd7634e5577a6199b279/preprocess.py#L182), which is called from [here](https://github.com/jgc128/mednli/blob/d7c9007a45a265dbfbb8cd7634e5577a6199b279/train_model.py#L193)

I think the easiest way to get those features is to just save these attention matrices by inserting something like 
```
save_pickle(DATA_DIR / 'umls_attention.pickled', (att_source_train, att_source_dev, att_target_dev, att_clinical_test))
```
after [this line](https://github.com/jgc128/mednli/blob/d7c9007a45a265dbfbb8cd7634e5577a6199b279/train_model.py#L234) and run the `python train_model.py with use_umls_attention=True use_token_level_attention=True`

After that, you can get these features by loading the pickle file and doing something like
```
features_att_mean = att_matrix.mean(axis=(1, 2))
features_att_max = att_matrix.max(axis=(1, 2))
features_att_min = att_matrix.min(axis=(1, 2))
```
